
$fn = 64; // Качество окружностей

GLOBAL_HEIGHT = 15;

// Aqara розетка
AQARA_DIAMETER = 60;
AQARA_BUTTON_DIAMETER = 12;
AQARA_RIM_THICKNESS = 3;
AQARA_RIM_INNER_D = AQARA_DIAMETER + 0.5;
AQARA_RIM_OUTER_D = AQARA_RIM_INNER_D + AQARA_RIM_THICKNESS * 2;

// ESP32
ESP32_WIDTH = 25.4;
ESP32_LENGTH = 53.3;
ESP32_HEIGHT = 13;
ESP32_WALL_THICKNESS = 2;

// Бобышка
BOSS_BASE_DIAMETER = 6;
BOSS_BASE_HEIGHT = 3;
BOSS_DIAMETER = 3;
BOSS_HEIGHT = 10;
